apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  default:
    predictor:
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
        resources:
            limits:
              cpu: 0.1
              memory: 100Mi
            requests:
              cpu: 0.1
              memory: 100Mi
