injector:
  enabled: false

server:
  dev:
    enabled: true

  dataStorage:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

  affinity: null
  tolerations: null
