injector:
  enabled: false

server:
  affinity: null

  dataStorage:
    enabled: false

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
