name: "Create cluster using KinD"
on: [pull_request, push]
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup cluster
      run: |
        ./setup_cluster.sh

    - name: Test KFServing installation
      run: |
        kubectl create namespace kfserving-test
        kubectl apply -f sklearn.yaml -n kfserving-test

        kubectl wait --for=condition=ready inferenceservice/sklearn-iris -n kfserving-test

        kubectl get svc istio-ingressgateway -n istio-system
