name: "Create cluster using KinD"
on: [pull_request, push]
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup cluster
      run: |
        ./setup_cluster.sh

    - name: Test KFServing installation
      run: |
        kubectl create namespace kfserving-test
        kubectl apply -f sklearn.yaml -n kfserving-test

        kubectl wait inferenceservice/sklearn-iris --for=condition=ready -n=kfserving-test --timeout=300s
        sleep 5
        curl http://sklearn-iris-predictor-default.kfserving-test.127.0.0.1.xip.io/v1/models/sklearn-iris:predict -d '{"instances":[[6.8,2.8,4.8,1.4],[6.0,3.4,4.5,1.6]]}'
