name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - uses: engineerd/setup-kind@v0.4.0
    #   with:
    #     version: "v0.8.1"
    #     config: kind-config.yaml
    - name: Setup Kind
      run: |
        whoami 
        sudo echo hello
        cat /etc/passwd
        kind create cluster --config=kind-config.yaml
    - name: Install Knative Serving
      run: |
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-crds.yaml
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-core.yaml
    - name: Install Knative Istio
      run: |
        ISTIO_VERSION=1.7.0 curl -sL https://istio.io/downloadIstio | sh -
        sudo install istio-1.7.0/bin/istioctl /usr/bin/istioctl
        istioctl install -f istio-minimal-operator.yaml
        kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.17.0/release.yaml
    - name: Test Ingress
      run: |
        kubectl apply -f test-ingress.yaml
        sleep 5
        kubectl get all,ingress
        sleep 30
        kubectl get all,ingress
        curl localhost/foo
        curl localhost/bar