name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - uses: engineerd/setup-kind@v0.4.0
    #   with:
    #     version: "v0.8.1"
    #     config: kind-config.yaml
    - name: Setup Kind
      run: |
        kind create cluster --config=kind-config.yaml
    # - name: Install Knative Serving
    #   run: |
    #     kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-crds.yaml
    #     kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-core.yaml
    
    - name: Install Knative serving
      run: |
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-crds.yaml
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.17.0/serving-core.yaml

    - name: Install Knative Istio
      run: |
        curl -sL https://istio.io/downloadIstio | ISTIO_VERSION=1.7.0 sh -
        sudo install istio-1.7.0/bin/istioctl /usr/bin/istioctl
        istioctl install -f istio-minimal-operator.yaml &
        for i in {1..10}; do sleep 10; kubectl -n istio-system get pods; done
        kubectl describe nodes
        # kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.17.0/release.yaml
        # kubectl patch configmap/config-domain \
        #   --namespace knative-serving \
        #   --type merge \
        #   --patch '{"data":{"127.0.0.1.xip.io":""}}'
    # - name: Test Ingress
    #   run: |
    #     kubectl apply -f test-ingress.yaml
    #     sleep 5
    #     kubectl get all,ingress
    #     sleep 30
    #     kubectl get all,ingress
    #     curl localhost/foo
    #     curl localhost/bar