name: "Create cluster using KinD"
on: [pull_request, push]
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Prepare cluster
      run: |
        echo "=== Create Cluster"
        kind create cluster
        sleep 10

        echo "=== Install Knative"
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.15.0/serving-crds.yaml
        kubectl apply --filename https://github.com/knative/serving/releases/download/v0.15.0/serving-core.yaml
        sleep 10

        echo "=== Install Istio"
        curl -sL https://istio.io/downloadIstio | ISTIO_VERSION=1.6.2 sh -
        sudo install istio-1.6.2/bin/istioctl /usr/bin/istioctl
        istioctl install -f istio-minimal-operator.yaml
        kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.15.0/release.yaml
        kubectl patch configmap/config-domain \
          --namespace knative-serving \
          --type merge \
          --patch '{"data":{"127.0.0.1.xip.io":""}}'
        kubectl get svc istio-ingressgateway -n istio-system
        sleep 10

        echo "=== Install Cert Manager"
        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
        kubectl wait --for=condition=available --timeout=600s deployment/cert-manager-webhook -n cert-manager

    - name: Install KFServing
      run: |
        kubectl apply --filename https://raw.githubusercontent.com/kubeflow/kfserving/master/install/v0.4.0/kfserving.yaml
        kubectl wait --for=condition=ready --timeout=600s pod/kfserving-controller-manager-0 -n kfserving-system

    - name: Test KFServing installation
      run: |
        kubectl create namespace kfserving-test
        kubectl apply -f https://raw.githubusercontent.com/kubeflow/kfserving/master/docs/samples/sklearn/sklearn.yaml -n kfserving-test

        sleep 180

        kubectl describe all -n kfserving-test
